#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "husky running..."

rm -f /tmp/chatdesignfailstatus

(
  npx lint-staged > /dev/null 2>&1 || {
    # bigfish-lib 非海兔资产提示，需要npm包目录下执行
    echo "------------------------"
  }
) &

# npx bigfish-lib doctor > /dev/null 2>&1 || {
#   # bigfish-lib 非海兔资产提示，需要npm包目录下执行
#   echo ""
# }

command_exists () {
  command -v "$1" >/dev/null 2>&1
}

# Check that npm exists
command_exists npm || {
  echo >&2 "husky > can't find npm in PATH, skipping test precommit in package.json"
  exit 0
}

# Run npm script
# echo "husky > npm run -s precommit (node `node -v`)"

(
  if npm run -s ci > /dev/null; then :
  else 
    echo true > /tmp/chatdesignfailstatus
    printf "husky > \033[31m tnpm run ci Error, ci 未通过, 请检查 \033[0m\n"
  fi
) &

(
  if npm run -s precommit > /dev/null 2>&1; then :
  else
    echo true > /tmp/chatdesignfailstatus
    printf "husky > \033[31m tnpm run test Error 有测试用例未通过, 请通过后再提交\033[0m\n"
  fi
) &

wait

if [ -f /tmp/chatdesignfailstatus ] && [ "$(cat /tmp/chatdesignfailstatus)" = "true" ]; then
  echo "husky > pre-commit hook failed (add --no-verify to bypass)"
  exit 1
else 
  COMMIT_INCLUDE_SNAPSHOTS=$(npx ts-node -e "import { includeSnapshots } from './jest.config'; console.log(includeSnapshots ? 'true' : 'false')") || {
    printf "\033[31m Warn: 未发现 './jest.config.ts export includeSnapshots: boolean 配置, 默认撤回所有缓冲区 *.snap 文件更改'\033[0m\n"
  }

  if [ "$COMMIT_INCLUDE_SNAPSHOTS" = "true" ]; then
    git add *.snap
  else
    git restore *.snap
  fi

  printf "husky > \033[32m checked pre-commit ok \033[0m\n"
fi
